# Java Multiple Questions
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (2,'1','Which of the following option leads to the portability and security of Java?',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (3,'1','Which of the following is not a Java features?',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (6,'1','The \\u0021 article referred to as a',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (7,'1','_____ is used to find and fix bugs in the Java programs.',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (8,'1','Which of the following is a valid declaration of a char?',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (9,'1','What is the return type of the hashCode() method in the Object class?',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (10,'1','Which of the following is a valid long literal?',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (11,'1','What does the expression float a = 35 / 0 return?',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (12,'1','Which of the following tool is used to generate API documentation in HTML format from doc comments in source code?',1,'0',NULL);
INSERT INTO quiz_website_hibernate.question (`question_id`,`is_active`,`question_content`,`quiz_type`,`is_short_question`,`short_question_answer`) VALUES (13,'1','Which of the following for loop declaration is not valid?',1,'0',NULL);


# Java Options
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (1,'1','Bytecode is executed by JVM',2);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (2,'0','The applet makes the Java code secure and portable',2);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (3,'0','Use of exception handling',2);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (4,'0','Dynamic binding between objects',2);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (5,'0','',2);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (6,'0','Dynamic',3);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (7,'0','Architecture Neutral',3);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (8,'0','Object-oriented',3);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (9,'1','Use of pointers',3);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (10,'0','',3);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (21,'1','Unicode escape sequence',6);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (22,'0','Octal escape',6);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (23,'0','Hexadecimal',6);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (24,'0','Line feed',6);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (25,'0','',6);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (26,'0','JVM',7);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (27,'0','JRE',7);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (28,'0','JDK',7);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (29,'1','JDB',7);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (30,'0','',7);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (31,'1','char ch = \'\\utea\';',8);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (32,'0','char ca = \'tea\';',8);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (33,'0','char cr = \\u0223;',8);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (34,'0','char cc = \'\\itea\';',8);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (35,'0','',8);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (36,'0','Object',9);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (37,'1','int',9);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (38,'0','long',9);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (39,'0','void',9);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (40,'0','',9);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (41,'0','ABH8097',10);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (42,'0','L990023',10);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (43,'0','904423',10);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (44,'1','0xnf029L',10);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (45,'0','',10);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (46,'0','0',11);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (47,'0','Not a Number',11);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (48,'1','Infinity',11);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (49,'0','Run time exception',11);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (50,'0','',11);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (51,'0','javap tool',12);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (52,'0','javaw command',12);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (53,'1','Javadoc tool',12);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (54,'0','javah command',12);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (55,'0','',12);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (56,'1','for ( int i = 99; i >= 0; i / 9 )',13);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (57,'0','for ( int i = 7; i <= 77; i += 7 )',13);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (58,'0','for ( int i = 20; i >= 2; - -i )',13);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (59,'0','for ( int i = 2; i <= 20; i = 2* i )',13);
INSERT INTO quiz_website_hibernate.questionoption (`option_id`,`is_answer`,`option_content`,`question_id`) VALUES (60,'0','',13);